### ISSUE TITLE
Проблемы с английским языком

### ISSUE THREAD

**Issue by Relz** [Reywam/TAaFL#2]
![image](https://user-images.githubusercontent.com/15068331/34122366-27d3de98-e424-11e7-8593-53666db72839.png)

**Comment by Relz** [comment]
![image](https://user-images.githubusercontent.com/15068331/34122377-30a8ad1e-e424-11e7-971e-89793ecb2d19.png)

**Comment by Relz** [comment]
![image](https://user-images.githubusercontent.com/15068331/34122389-37ff2002-e424-11e7-83cf-ddc8910b1cea.png)

**Comment by Hemul997** [comment]
Время почувствовать себя Маловым:D

**Comment by vomikay** [comment]
Perfect English 💃
